<div class="login">
	<?= '<p class="red">'.$error.'</p>' ?>
</div>
<div class="login">
	<h1>Inscription</h1>
    <form method="post">
    	<input type="text" name="u" placeholder="Pseudo" required="required" />
    	<input type="email" name="m" placeholder="Adresse mail" required="required" />
    	<input type="email" name="m2" placeholder="Adresse mail confirmation" required="required" />
        <input type="password" name="p" placeholder="Mot de passe" required="required" />
        <input type="password" name="p2" placeholder="Mot de passe confirmation" required="required" />
        <button type="submit" name="register" class="btn btn-primary btn-block btn-large">M'enregistrer</button>
    </form>
</div>